CREATE TABLE stock
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id     UUID      DEFAULT RANDOM_UUID() NOT NULL UNIQUE,
    stock_year    INTEGER,
    product_id    UUID,
    quantity      INTEGER,
    average_price DECIMAL(19, 4),
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by    VARCHAR(255),
    modified_at   TIMESTAMP WITH TIME ZONE,
    modified_by   VARCHAR(255)
);

CREATE TABLE stock_movement
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID DEFAULT RANDOM_UUID() NOT NULL UNIQUE,
    movement_date DATE,
    stock_id      UUID,
    movement_type VARCHAR(50),
    quantity      INTEGER,
    price         DECIMAL(19, 4),
    reason        VARCHAR(512),
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by    VARCHAR(255),
    modified_at   TIMESTAMP WITH TIME ZONE,
    modified_by   VARCHAR(255)
);

