CREATE TABLE product
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id       UUID      DEFAULT RANDOM_UUID() NOT NULL UNIQUE,
    name            VARCHAR(255),
    default_price   DECIMAL(19, 4),
    unit            VARCHAR(50),
    category        VARCHAR(50),
    attributes_json VARCHAR(2048),
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by      VARCHAR(255),
    modified_at     TIMESTAMP WITH TIME ZONE,
    modified_by     VARCHAR(255)
);

INSERT INTO product (name, unit, category, attributes_json)
VALUES ('Pot Vide 1KG', 'UNIT', 'EMPTY_JAR', '{"SIZE": "1KG"}');
INSERT INTO product (name, unit, category, attributes_json)
VALUES ('Pot Vide 500G', 'UNIT', 'EMPTY_JAR', '{"SIZE": "500G"}');
INSERT INTO product (name, unit, category)
VALUES ('Barquette Vide', 'UNIT', 'EMPTY_TRAY');
INSERT INTO product (name, unit, category)
VALUES ('Miel Vrac', 'GRAM', 'BULK_HONEY');
INSERT INTO product (name, unit, category)
VALUES ('Reine', 'UNIT', 'QUEEN');
