CREATE TABLE customer (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id   UUID DEFAULT RANDOM_UUID() NOT NULL UNIQUE,
    firstname   VARCHAR(255),
    lastname    VARCHAR(255),
    email       VARCHAR(255) UNIQUE,
    phone       VARCHAR(20),
    street      VARCHAR(255),
    postal_code VARCHAR(20),
    city        VARCHAR(255),
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by  VARCHAR(255),
    modified_at TIMESTAMP WITH TIME ZONE,
    modified_by VARCHAR(255)
);

INSERT INTO customer (firstname, lastname, created_by) VALUES ('Fabien', 'ALLEMAND', 'system');
INSERT INTO customer (firstname, lastname, created_by) VALUES ('Carine', 'MARINELLO', 'system');